name: 'Terraform CDK Pattern Action'
description: 'Runs Terraform CDK commands against a stack in a given workspace.'
author: 'TrueMark'
branding:
  icon: 'check-circle'
  color: 'red'

inputs:
  mode:
    required: true
    description: 'A list of actions to run against the Terraform CDK stack. Options are plan and deploy.'
  stack-name:
    required: true
    description: 'The name of the Terraform CDK stack to run commands against'
  working-directory:
    required: false
    description: 'The directory where Terraform CDK lives'
    default: .
  workspace:
    required: false
    description: 'The workspace in which to plan or deploy the stack. Providing one triggers a cdk synth'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Terraform CDK globally
      shell: bash
      run: |
        npm cache verify
        npm install --global cdktf-cli@0.17.1

    - name: Terraform CDK synth
      if: ${{ inputs.workspace != '' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: cdktf synth
      env:
        TF_WORKSPACE: ${{ inputs.workspace }}

    # This step is required to create or select a workspace within the cdktf context.
    # TF_WORKSPACE cannot be set as an environment variable for this step or else cdktf will not behave correctly.
    - name: Create Terraform Workspace
      if: ${{ inputs.workspace != '' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}/cdktf.out/stacks/${{ inputs.stack-name }}
      run: |
        terraform init
        terraform workspace select ${{ inputs.workspace }} || terraform workspace new ${{ inputs.workspace }}

    - name: Run Terraform CDK plan
      shell: bash
      if: ${{ contains(inputs.mode, 'plan') }}
      working-directory: ${{ inputs.working-directory }}
      run: cdktf plan
      env:
        TF_WORKSPACE: ${{ inputs.workspace }}

    - name: Run Terraform CDK deploy
      shell: bash
      if: ${{ contains(inputs.mode, 'deploy') }}
      working-directory: ${{ inputs.working-directory }}
      run: cdktf deploy --auto-approve
      env:
        TF_WORKSPACE: ${{ inputs.workspace }}
